src/blog/urls.py
from django.urls import path

from blog.views import (
    DeletePostView,
    DetailPostView,
    EditPostView,
    ListPostView,
    NewPostView,
)

app_name = "blog"

urlpatterns = [
    path("", ListPostView.as_view(), name="index"),
    path("new", NewPostView.as_view(), name="new"),
    path("<uuid:pk>/", DetailPostView.as_view(), name="detail"),
    path("<uuid:pk>/edit", EditPostView.as_view(), name="edit"),
    path("<uuid:pk>/delete", DeletePostView.as_view(), name="delete"),
]

src/myproject/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
    path("blog/", include("blog.urls")),
    path("projects/", include("projects.urls")),
    path("", lambda request: render(request, "index.html"), name="index"),
]

src/tm/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("tasks/", include("tasks.urls")),
]

src/blog/models.py
import uuid

from django.db import models

# Create your models here.

POST_SUMMARY_LENGTH = 100


class Post(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    author = models.ForeignKey("accounts.User", on_delete=models.CASCADE)
    title = models.CharField(max_length=256)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"({self.id}){self.title}"

    @property
    def sumamry(self) -> str:
        if len(self.content) > POST_SUMMARY_LENGTH:
            summary_len = POST_SUMMARY_LENGTH - 3
            return self.content[:summary_len] + "..."
        return self.content

src/blog/forms.py
from django.forms import ModelForm

from blog.models import Post


class NewPostForm(ModelForm):
    class Meta:
        model = Post
        fields = (
            "title",
            "content",
        )


class EditPostForm(ModelForm):
    class Meta:
        model = Post
        fields = (
            "title",
            "content",
        )

src/blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.query import QuerySet
from django.http.response import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView
from django.views.generic.edit import UpdateView

from blog.forms import EditPostForm, NewPostForm
from blog.models import Post


class DetailPostView(DetailView, LoginRequiredMixin):
    model = Post
    template_name = "blog/detail.html"
    context_object_name = "post"


class NewPostView(CreateView, LoginRequiredMixin):
    model = Post
    template_name = "blog/new.html"
    form_class = NewPostForm

    def form_valid(self, form: NewPostForm) -> HttpResponse:
        post = form.save(commit=False)
        post.author = self.request.user
        post.save()
        return HttpResponseRedirect(reverse("blog:detail", kwargs={"pk": post.pk}))


class EditPostView(UpdateView, LoginRequiredMixin):
    model = Post
    template_name = "blog/edit.html"
    form_class = EditPostForm
    context_object_name = "post"

    def get_queryset(self) -> QuerySet:
        return self.model.objects.filter(author=self.request.user).all()

    def get_success_url(self) -> str:
        assert self.object is not None
        return reverse("blog:detail", kwargs={"pk": self.object.pk})


class ListPostView(ListView, LoginRequiredMixin):
    model = Post
    template_name = "blog/index.html"
    context_object_name = "posts"

    def get_queryset(self) -> QuerySet:
        signed_in_user = self.request.user
        return (
            self.model.objects.filter(author=signed_in_user)
            .all()
            .order_by("-created_at")
        )


class DeletePostView(DeleteView, LoginRequiredMixin):
    template_name = "blog/confirm_delete.html"
    success_url = reverse_lazy("blog:index")
    context_object_name = "post"

    def get_queryset(self) -> QuerySet:
        user = self.request.user
        assert user.is_authenticated

        return Post.objects.filter(author=user).all()

src/templates/blog/confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    <p>Will you delete
      <b>{{ post.id }}/{{ post.title }}</b>
      ?
    </p>
    <input type="submit" value="DELETE">
  </form>
{% endblock %}

src/templates/blog/detail.html
{% extends "base.html" %}

{% block content %}
  <h2>{{ post.title }}</h2>
  <a href="{% url 'blog:edit' pk=post.id %}">EDIT</a>
  <a href="{% url 'blog:delete' pk=post.id %}">DELETE</a>
  <hr>
  <div>
    {{ post.content|linebreaks }}
  </div>
{% endblock %}

src/templates/blog/edit.html
{% extends "base.html" %}

{% block content %}
  <form method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <div>
      <a href="{% url 'blog:detail' pk=post.id %}">CANCEL</a>
      <input type="submit" value="EDIT">
    </div>
  </form>
{% endblock %}

src/templates/blog/index.html
{% extends "base.html" %}

{% block content %}
  <div>
    <h4>My Posts</h4>
    <div>
      <a href="{% url 'blog:new' %}">New Post</a>
    </div>
    {% for post in posts %}
      <div class="card">
        <a href="{% url 'blog:detail' pk=post.id %}">{{ post.title }}</a>
        <p>{{ post.content }}</p>
      </div>
      {% empty %}
      <div>
        <p>No Posts...</p>
      </div>
    {% endfor %}
  </div>
{% endblock %}

src/templates/blog/new.html
{% extends "base.html" %}

{% block content %}
  <div>
    <h4>Create a new Post</h4>
    <form method="post">
      {% csrf_token %}
      <table>{{ form.as_table }}</table>

      <div>
        <a href="{% url 'blog:index' %}">CANCEL</a>
        <input type="submit" value="NEW POST">
      </div>
    </form>
  </div>
{% endblock %}