src/accounts/urls.py
from django.urls import path

from .views import SignInFormView, SignUpFormView, index, signout

app_name = "accounts"

urlpatterns = [
    path("", index, name="index"),
    path("signup", SignUpFormView.as_view(), name="signup"),
    path("signin", SignInFormView.as_view(), name="signin"),
    path("signout", signout, name="signout"),
]

src/myproject/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
    path("blog/", include("blog.urls")),
    path("projects/", include("projects.urls")),
    path("", lambda request: render(request, "index.html"), name="index"),
]

src/tm/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("tasks/", include("tasks.urls")),
]

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'utils/css/atoms/theme.css' %}">
    <link rel="stylesheet" href="{% static 'utils/css/atoms/card.css' %}">
    <link rel="stylesheet" href="{% static 'utils/css/atoms/tag.css' %}">
    <link rel="stylesheet" href="{% static 'utils/css/molecules/task_status.css' %}">
    <link rel="stylesheet" href="{% static 'utils/css/molecules/tag_list.css' %}">
    <title>MyProject</title>
  </head>

  <body>
    <header>
      <h1>MyProject</h1>
      <ul>
        {% if user.is_authenticated %}
          <li>
            <a href="{% url 'accounts:signout' %}">SIGN OUT</a>
          </li>
        {% else %}
          <li>
            <a href="{% url 'accounts:signin' %}">SIGN IN</a>
          </li>
          <li>
            <a href="{% url 'accounts:signup' %}">SIGN UP</a>
          </li>
        {% endif %}
      </ul>
    </header>

    {% include "components/nav.html" %}

    <main>
      {% block content %}{% endblock %}
    </main>

    <script src="{% static 'tasks/js/assign_me.js' %}" type="text/javascript"></script>
  </body>

</html>

src/templates/constructing.html
{% extends "base.html" %}

{% block content %}
  <p>This page is constructing...</p>
{% endblock %}

src/templates/index.html
{% extends "base.html" %}

{% block content %}
  <h2>Top Page</h2>
{% endblock %}