src/myproject/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
    path("blog/", include("blog.urls")),
    path("projects/", include("projects.urls")),
    path("", lambda request: render(request, "index.html"), name="index"),
]

src/projects/urls.py
from django.urls.conf import path

from projects.views import (
    DeleteProjectView,
    DetailProjectView,
    EditProjectView,
    ListProjectsView,
    NewProjectView,
)

app_name = "projects"

urlpatterns = [
    path("", ListProjectsView.as_view(), name="index"),
    path("new/", NewProjectView.as_view(), name="new"),
    path("<uuid:pk>/", DetailProjectView.as_view(), name="detail"),
    path("<uuid:pk>/edit", EditProjectView.as_view(), name="edit"),
    path("<uuid:pk>/delete", DeleteProjectView.as_view(), name="delete"),
]

src/tm/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("tasks/", include("tasks.urls")),
]

src/projects/models.py
import re
import uuid

from django.core.validators import RegexValidator
from django.db import models
from django.utils.deconstruct import deconstructible
from django.utils.translation import ugettext_lazy as _

# Create your models here.


@deconstructible
class VersionValidator(RegexValidator):
    regex = r"^[0-9]+.[0-9]+.[0-9]+$"
    message = (
        "Enter a valid version. This value should be <major>.<minor>.<patch>, and"
        " all fields should contain only numbers."
    )
    flags = re.ASCII


class Project(models.Model):
    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    name = models.CharField(max_length=128)
    owner = models.ForeignKey(
        "accounts.User",
        on_delete=models.CASCADE,
        related_name="projects",
    )
    elevator_pitch = models.CharField(
        _("short summary of what you want to achieve"),
        max_length=512,
    )
    version = models.CharField(
        max_length=32,
        validators=[VersionValidator],
        default="0.0.0",
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name

src/projects/forms.py
from django.forms import ModelForm

from projects.models import Project


class NewProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = (
            "name",
            "elevator_pitch",
        )


class EditProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = (
            "name",
            "elevator_pitch",
            "version",  # TODO version should be updated via milestone / sprint
        )

src/projects/views.py
from typing import Any, Dict

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.query import QuerySet
from django.http.response import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView, UpdateView

from projects.forms import EditProjectForm, NewProjectForm
from projects.models import Project
from tasks.models import Status

# Create your views here.


class NewProjectView(CreateView, LoginRequiredMixin):
    template_name = "projects/new.html"
    model = Project
    form_class = NewProjectForm

    def form_valid(self, form: NewProjectForm) -> HttpResponse:
        project: Project = form.save(commit=False)
        project.owner = self.request.user
        project.save()
        return HttpResponseRedirect(
            reverse("projects:detail", kwargs={"pk": project.pk}),
        )


class ListProjectsView(ListView, LoginRequiredMixin):
    template_name = "projects/index.html"
    model = Project
    context_object_name = "projects"

    def get_queryset(self) -> QuerySet:
        return self.model.objects.filter(owner=self.request.user).all()


class DetailProjectView(DetailView, LoginRequiredMixin):
    template_name = "projects/detail.html"
    model = Project
    context_object_name = "project"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context_data = super().get_context_data(**kwargs)
        task_status = self.request.GET.get("status", Status.WIP)
        context_data["tasks"] = self.object.tasks.filter(status=task_status)
        return context_data


class EditProjectView(UpdateView, LoginRequiredMixin):
    template_name = "projects/edit.html"
    model = Project
    form_class = EditProjectForm
    context_object_name = "project"

    def get_success_url(self) -> str:
        return reverse_lazy("projects:detail", kwargs={"pk": self.object.pk})


class DeleteProjectView(DeleteView, LoginRequiredMixin):
    template_name = "projects/confirm_delete.html"
    model = Project
    context_object_name = "project"
    success_url = reverse_lazy("projects:index")

src/templates/projects/confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    <p>Will you delete
      <b>{{ project.name }}</b>
      ?
    </p>
    <a href="{% url 'projects:detail' pk=project.id %}">CANCEL</a>
    <input type="submit" value="DELETE">
  </form>
{% endblock %}

src/templates/projects/detail.html
{% extends "base.html" %}

{% block content %}
  <div>
    <h2>{{ project.name }}</h2>
    <div>
      <a href="{% url 'projects:edit' pk=project.id %}">EDIT</a>
      <a href="{% url 'projects:delete' pk=project.id %}">DELETE</a>
    </div>
    <p>
      <b>Latest Version:</b>
      {{ project.version }}
    </p>

    <div>
      <p>
        <b>Elevator Pitch</b>
      </p>
      <p>{{ project.elevator_pitch }}</p>
    </div>

    <div>
      <h4>Tasks</h4>
      {% include "components/organizations/task_list.html" %}
    </div>
  </div>
{% endblock %}

src/templates/projects/edit.html
{% extends "base.html" %}

{% block content %}
  <form method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>

    <a href="{% url 'projects:detail' pk=project.id %}">CANCEL</a>
    <input type="submit" value="EDIT">
  </form>
{% endblock %}

src/templates/projects/index.html
{% extends "base.html" %}

{% block content %}
  <div>
    <h4>Your Projects</h4>

    <div>
      <a href="{% url 'projects:new' %}">Create a new Project!</a>
    </div>

    <div>
      {% for project in projects %}
        <div class="card">
          <a href="{% url 'projects:detail' pk=project.id %}">{{ project.name }}</a>
          <p>{{ project.elevator_pitch }}</p>
          <p>v{{ project.version }}</p>
        </div>
        {% empty %}
        <div>
          <p>No projects...</p>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

src/templates/projects/new.html
{% extends "base.html" %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>

    <a href="{% url 'projects:index' %}">CANCEL</a>
    <input type="submit" value="CREATE">
  </form>
{% endblock %}