src/myproject/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
    path("blog/", include("blog.urls")),
    path("projects/", include("projects.urls")),
    path("", lambda request: render(request, "index.html"), name="index"),
]

src/tasks/urls.py
from django.urls import path

from tasks.views import DeleteTaskView, EditTaskView, NewTaskView, TaskListView

app_name = "tasks"

urlpatterns = [
    path("new", NewTaskView.as_view(), name="new"),
    path("<uuid:parent_id>/new", NewTaskView.as_view(), name="new-subtask"),
    path("<uuid:pk>/edit", EditTaskView.as_view(), name="edit"),
    path("<uuid:pk>/delete", DeleteTaskView.as_view(), name="delete"),
    path("", TaskListView.as_view(), name="index"),
]

src/tm/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("tasks/", include("tasks.urls")),
]

src/templates/components/organizations/task_list.html
{% load task_tags %}

<div class="task-list">
  <div class="task-list-tabs">
    <!-- unibeautify:disable -->
    {% with statuses='TODO WIP DONE' %}
    {% for status in statuses.split %}
      <a href="{{ request.path }}?status={{ status|lower }}">{{ status|upper }}</a>
    {% endfor %}
    {% endwith %}
  </div>
  <div class="task-list-container">
    {% for task in tasks %}
      <div>
        <div class="card">
          <a href="{% url 'tasks:edit' pk=task.id %}">{{ task.name }}</a>
          <div>
            <!-- unibeautify:disable -->
            {% include "components/molecules/tag_list.html" with tags=task|task_tags only %}
            <!-- unibeautify:enable -->
          </div>
          <p class="secondary-text">
            {% if task.detail %}
              {{ task.detail }}
            {% else %}
              No description.
            {% endif %}
          </p>
          <a href="{% url 'tasks:new-subtask' parent_id=task.id %}">SPLIT</a>
          <a href="{% url 'tasks:delete' pk=task.id %}?prev={{ request.get_full_path|urlencode }}">DELETE</a>
        </div>
      </div>
      {% empty %}
      <div>
        <p>No tasks</p>
      </div>
    {% endfor %}
  </div>
</div>